
import __ASTRO_IMAGE_IMPORT_OF4qE from "../../assets/images/team/antonia.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fantonia.json";
import __ASTRO_IMAGE_IMPORT_Z1VuNyK from "../../assets/images/team/chris_und_nalini.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fchris_und_nalini.json";
import __ASTRO_IMAGE_IMPORT_19yDkG from "../../assets/images/team/janis.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fjanis.json";
import __ASTRO_IMAGE_IMPORT_Z1lAqEb from "../../assets/images/team/katharina.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fkatharina.json";
import __ASTRO_IMAGE_IMPORT_Za8pfT from "../../assets/images/team/omar.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fomar.json";
import __ASTRO_IMAGE_IMPORT_2fYBSd from "../../assets/images/team/pancho_und_anna.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fpancho_und_anna.json";
import __ASTRO_IMAGE_IMPORT_1d5bU1 from "../../assets/images/team/patricia.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fpatricia.json";
import __ASTRO_IMAGE_IMPORT_Z1pU7mU from "../../assets/images/team/sebastian.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fsebastian.json";
import __ASTRO_IMAGE_IMPORT_Z1ODjIq from "../../assets/images/team/silke.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fsilke.json";
import __ASTRO_IMAGE_IMPORT_ZR1Tnf from "../../assets/images/team/stephan.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fstephan.json";
import __ASTRO_IMAGE_IMPORT_1Inuda from "../../assets/images/team/vicky.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fvicky.json";
import __ASTRO_IMAGE_IMPORT_Z16vza3 from "../../assets/images/testimonials/bg.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fneuer-kurs-mai.md";
import __ASTRO_IMAGE_IMPORT_19kAkj from "../../assets/images/testimonials/hugo.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftestimonials%2Fhugo.json";
import __ASTRO_IMAGE_IMPORT_pGOjV from "../../assets/images/testimonials/jorge.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftestimonials%2Fjorge.json";
import __ASTRO_IMAGE_IMPORT_jtACT from "../../assets/images/testimonials/melanie.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftestimonials%2Fmelanie.json";
import __ASTRO_IMAGE_IMPORT_vwJ5a from "../../assets/images/testimonials/susy.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftestimonials%2Fsusy.json";
import __ASTRO_IMAGE_IMPORT_ZCW41m from "../../assets/images/workshops/bailabachata.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworkshops%2Fbailabachata.json";
import __ASTRO_IMAGE_IMPORT_1Wkdre from "../../assets/images/workshops/habibi-amor.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworkshops%2Fhabibi-amor.json";
export default new Map([["../../assets/images/team/antonia.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fantonia.json", __ASTRO_IMAGE_IMPORT_OF4qE], ["../../assets/images/team/chris_und_nalini.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fchris_und_nalini.json", __ASTRO_IMAGE_IMPORT_Z1VuNyK], ["../../assets/images/team/janis.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fjanis.json", __ASTRO_IMAGE_IMPORT_19yDkG], ["../../assets/images/team/katharina.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fkatharina.json", __ASTRO_IMAGE_IMPORT_Z1lAqEb], ["../../assets/images/team/omar.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fomar.json", __ASTRO_IMAGE_IMPORT_Za8pfT], ["../../assets/images/team/pancho_und_anna.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fpancho_und_anna.json", __ASTRO_IMAGE_IMPORT_2fYBSd], ["../../assets/images/team/patricia.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fpatricia.json", __ASTRO_IMAGE_IMPORT_1d5bU1], ["../../assets/images/team/sebastian.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fsebastian.json", __ASTRO_IMAGE_IMPORT_Z1pU7mU], ["../../assets/images/team/silke.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fsilke.json", __ASTRO_IMAGE_IMPORT_Z1ODjIq], ["../../assets/images/team/stephan.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fstephan.json", __ASTRO_IMAGE_IMPORT_ZR1Tnf], ["../../assets/images/team/vicky.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fvicky.json", __ASTRO_IMAGE_IMPORT_1Inuda], ["../../assets/images/testimonials/bg.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fneuer-kurs-mai.md", __ASTRO_IMAGE_IMPORT_Z16vza3], ["../../assets/images/testimonials/hugo.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftestimonials%2Fhugo.json", __ASTRO_IMAGE_IMPORT_19kAkj], ["../../assets/images/testimonials/jorge.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftestimonials%2Fjorge.json", __ASTRO_IMAGE_IMPORT_pGOjV], ["../../assets/images/testimonials/melanie.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftestimonials%2Fmelanie.json", __ASTRO_IMAGE_IMPORT_jtACT], ["../../assets/images/testimonials/susy.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftestimonials%2Fsusy.json", __ASTRO_IMAGE_IMPORT_vwJ5a], ["../../assets/images/workshops/bailabachata.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworkshops%2Fbailabachata.json", __ASTRO_IMAGE_IMPORT_ZCW41m], ["../../assets/images/workshops/habibi-amor.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworkshops%2Fhabibi-amor.json", __ASTRO_IMAGE_IMPORT_1Wkdre]]);
		